### ISSUE TITLE
Support for new users

### ISSUE THREAD

**Issue by BitLoose** [CherryUSB/cherryusb_stm32#1]
How can new users be supported?
Are there any code examples with different CPU/MCUs?
Is there a user group on Facebook?
I hope you don't mind me posting this as an "issue", but there is little in the readme to get anyone started.
The MX comment about main.c just requires the #user code defines to be added to protect the critical code.

**Comment by sakumisu** [comment]
We have only chinese docs: https://cherryusb.readthedocs.io/zh-cn/latest/

**Comment by sakumisu** [comment]
No need to support different cpu because they have the same usb ips.

**Comment by sakumisu** [comment]
It is difficult to visit outer net, so we have no facebook. Sorry.
