### ISSUE TITLE
Cannot compile under CubeMX

### ISSUE THREAD

**Issue by Eqqm4n** [CherryUSB/cherryusb_stm32#2]
Hello-
We recently attempted to compile this code under CubeMX but failed.  The intended chip is the STM32F411.  After using CubeMX to generate the project and adding the CherryUSB files our version of the project fails to compile with this error-

#error "<dirent.h> not supported"

Researching this online the default toolchain needs to be set to use a different compiler.  What is the correct one to use?

**Comment by sakumisu** [comment]
I do not know, we do not use dirent.h, you can use my demo project.

**Comment by Eqqm4n** [comment]
Hello-
We seem to be having some strange issues with CubeMX.  It insists on compiling projects with the U5 software package rather than the F4 (which leads to the error on dirent.h).  Also, if the project file from the usb_host\stm32f429igt6\ folder is either directly opened or imported, the IDE does not provide any options to actually compile the code.

What FreeRTOS and USB Host settings must be enabled under Cube if we are to make a new project from scratch and try to add your files to that project?  If I pick "create project from existing IOC file" and use your stm32f429igt6.ioc file, nothing is turned on for either of these.

On a different note, if you have a way to add the "Discussion" tab to this project I will post these things there rather than have to put them in the bug report list.

**Comment by Eqqm4n** [comment]
Hello-
We possibly have the issue resolve of Cube trying to compile with the wrong firmware.  After resolving this we still don't have a complete build going.  It should be noted that although this STM32 git sub-project appears to link back to the core CherryUSB project, these core files don't get included when I download the sub-project as code.  After extracting the archive there is a CherryUSB sub-folder that exists but it is empty with no files in it.

Going to the readthedocs website we did find the explanation for the Cube setup with some pictures.  These directions state "Copy the contents of the HAL_PCD_MspInit function in xxx_msp.c to the usb_hc_low_level_init function, and shield the usb initialization generated by st".  However, usb_hc_low_level_init did not exist in the usb_glue_st.c file as stated, it only exists in the usb_glue_esp.c file.  Rather than try to add this function to the usb_glue_st.c file we tried letting the original call to the HAL USB init driver stand.

Our new error is-
C:/ST/Workspaces/cherry_usb_f411/Debug/../Core/CherryUSB/osal/usb_osal_freertos.c:28: undefined reference to `xQueueCreateCountingSemaphore'...

...which makes it seem as if some of the FreeRTOS files are missing.  As mentioned earlier it is not clear what settings need to be enabled in Cube for FreeRTOS to be added correctly.

We are also curious if you think CherryUSB would work on the STM32 U575 or L476?

**Comment by sakumisu** [comment]
- cherryusb is a submodule in this project, please use git submodule
- usb_hc_low_level_init is implemented by yourself ,thank you. for example
https://github.com/CherryUSB/cherryusb_stm32/blob/9f51cd5b8db7d382a539634a7aa635eebf8510a4/usb_host/stm32f429igt6/Core/Src/main.c#L71
- freertos sources are in cherryusb third party or you can use other freertos version from freertos official.

**Comment by sakumisu** [comment]
And i think all of these are your own problems. For examples, cherryusb depends on freertos, you should study freertos and then add them into your project, when you build failed, you should ask yourself not mine. Than you.

**Comment by sakumisu** [comment]
You should create an original code with freertos and printf work, then add cherryusb, for now, your original code is bad, so please do not add cherryusb.

**Comment by Eqqm4n** [comment]
> You should create an original code with freertos and printf work, then add cherryusb, for now, your original code is bad, so please do not add cherryusb.

Thank you. we will try these steps.  I should point out that when you say "your original code is bad" that we have no original code, we are trying to work with the CherryUSB STM32 source provided on this site and there is no code of our own there to begin with.

**Comment by Eqqm4n** [comment]
Hello-
Our preferred development environment is Segger Embedded Studio, however, we had difficulty getting this to run a FreeRTOS project as the FreeRTOS directions direct the use of functions that are not generated by SES.  As a consequence we were obligated to try and get things running under Cube.

We started a Cube project for the STM32L476 as this is the only chip we have access to that supports DMA and the CherryUSB documents imply this is a requirement for hosting.  However, the DMA options in Cube don't appear to allow for the DMA to be attached to the USB peripheral (see attached image).  As a consequence we left it on the "mem to mem" setting.
![cube_DMA](https://github.com/CherryUSB/cherryusb_stm32/assets/141067205/8c107b45-58eb-482c-99de-8cdf99c3c11f)

After using the IDE package manager to download their FreeRTOS support package we ran a project that successfully outputs text over the UART to a TeraTerm window in a thread.  Naturally, the FreeRTOS function calls used in the CherryUSB example code now no longer match what was generated by code.  For example, CherryUSB uses vTaskStartScheduler(); but the Cube-generated code was osKernelInitialize(); followed by osKernelStart();.  Be that as it may we continued to follow the STM32 porting directions.  At our current project state the IDE is flagging an error on usbh_class_info not being defined.  We did add the code 
```	/* section information for usbh class */
	. = ALIGN(4);
	__usbh_class_info_start__ = .;
	KEEP(*(.usbh_class_info))
	__usbh_class_info_end__ = .;
```

...to the RAM LD file (Cube is now generating separate linker files for the RAM and Flash).  Looking around also at what is being defined our code is compiling with this option:
```
#elif defined(__GNUC__)
#define CLASS_INFO_DEFINE __attribute__((section(".usbh_class_info"))) __USED __ALIGNED(1)
```

It should be noted the ReadTheDocs section for working with Cube says to set the toolchain to use MDK-ARM as the compiler, however, adjusting this is not an option as this is greyed out and not available to be changed:
![compiler_option](https://github.com/CherryUSB/cherryusb_stm32/assets/141067205/04b6364a-8d7d-4c3b-ad9e-74177452d6dc)

We looked at the Cube package manager and there did not appear to be an option for downloading additional compilers.  At this point it is not clear how to proceed.
